
REM mklink /d C:\NGSMS\Endeavour\MODULES\DOMAINS\VIDEO\FEA\FEA-05\BP F:\BP
REM mklink /d C:\NGSMS\Endeavour\MODULES\DOMAINS\VIDEO\FEA\FEA-05\ASSETS F:\ASSETS 

REM mklink /d C:\NGSMS\Endeavour\MODULES\DOMAINS\VIDEO\INT\INT-TEST\BP F:\BP
REM mklink /d C:\NGSMS\Endeavour\MODULES\DOMAINS\VIDEO\INT\INT-TEST\ASSETS F:\ASSETS 

REM mklink /d C:\NGSMS\Endeavour\MODULES\DOMAINS\TRACKING\FEA\FEA-01\BP F:\BP
REM mklink /d C:\NGSMS\Endeavour\MODULES\DOMAINS\TRACKING\FEA\FEA-01\ASSETS F:\ASSETS 

REM mklink /d C:\NGSMS\Endeavour\MODULES\APPS\OPERATORCLIENT\INT\INT\BP F:\BP
REM mklink /d C:\NGSMS\Endeavour\MODULES\APPS\OPERATORCLIENT\INT\INT\ASSETS F:\ASSETS 

REM mklink /d C:\NGSMS\Endeavour\MODULES\APPS\OPERATORCLIENT\FEA\FEA-02\BP F:\BP
REM mklink /d C:\NGSMS\Endeavour\MODULES\APPS\OPERATORCLIENT\FEA\FEA-02\ASSETS F:\ASSETS 

REM mklink /d C:\NGSMS\Endeavour\MODULES\DOMAINS\TRACKING\FEA\FEA-02\BP F:\BP
REM mklink /d C:\NGSMS\Endeavour\MODULES\DOMAINS\TRACKING\FEA\FEA-02\ASSETS F:\ASSETS 

REM mklink /d c:\NGSMS\Endeavour\MODULES\DOMAINS\TRACKING\FEA\FEA-03\BP F:\BP
REM mklink /d c:\NGSMS\Endeavour\MODULES\DOMAINS\TRACKING\FEA\FEA-03\ASSETS F:\ASSETS 

REM mklink /d C:\NGSMS\Endeavour\MODULES\DOMAINS\TRACKING\INT\INT\BP F:\BP
REM mklink /d C:\NGSMS\Endeavour\MODULES\DOMAINS\TRACKING\INT\INT\ASSETS F:\ASSETS 

REM mklink /d F:\OPCL\INT\INT\BP F:\BP
REM mklink /d F:\OPCL\INT\INT\ASSETS F:\ASSETS 

REM mklink /d C:\Users\wey1sgp\Source\Repos\VFCS\LAB\BP F:\BP
REM mklink /d C:\Users\wey1sgp\Source\Repos\VFCS\LAB\ASSETS F:\ASSETS

REM mklink /d c:\NGSMS\Endeavour\MODULES\DOMAINS\TRACKING\FEA\FEA-04\BP F:\BP
REM mklink /d c:\NGSMS\Endeavour\MODULES\DOMAINS\TRACKING\FEA\FEA-04\ASSETS F:\ASSETS

REM mklink /d c:\NGSMS\Endeavour\MODULES\APPS\OPERATORCLIENT\FEA\FEA-04\BP F:\BP
REM mklink /d c:\NGSMS\Endeavour\MODULES\APPS\OPERATORCLIENT\FEA\FEA-04\ASSETS F:\ASSETS

REM mklink /d c:\NGSMS\Endeavour\MODULES\DOMAINS\TRACKING\INT\INT-TEST\BP F:\BP
REM mklink /d c:\NGSMS\Endeavour\MODULES\DOMAINS\TRACKING\INT\INT-TEST\ASSETS F:\ASSETS

REM mklink /d C:\NGSMS\Endeavour\MODULES\DOMAINS\VIDEO\FEA\FEA-03\BP F:\BP
REM mklink /d C:\NGSMS\Endeavour\MODULES\DOMAINS\VIDEO\FEA\FEA-03\ASSETS F:\ASSETS 

REM mklink /d c:\NGSMS\Endeavour\PLATFORM\FEA\FEA-04\BP F:\BP
REM mklink /d c:\NGSMS\Endeavour\PLATFORM\FEA\FEA-04\ASSETS F:\ASSETS 

mklink /d C:\NGSMS\Endeavour\PLATFORM\INT\INT-FIER\BP F:\BP
mklink /d C:\NGSMS\Endeavour\PLATFORM\INT\INT-FIER\ASSETS F:\ASSETS 

